name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: msys2/setup-msys2@v2
    - name: Install dependencies
      run: choco install yasm
      
    - name: Clone FFmpeg
      shell: cmd
      run: |
        git clone https://github.com/FFmpeg/FFmpeg.git
        mkdir upload

    - name: Delete wrong link.exe
      shell: msys2 {0}
      run: >-
        which link.exe
        
    - name: Build library
      working-directory: ${{github.workspace}}/FFmpeg
      shell: msys2 {0}
      run: |
        rm /usr/bin/link.exe
        ./configure '
        --target-os=win64 '
        --toolchain=msvc '
        --prefix=${{github.workspace}}\upload '
        --enable-gpl '
        --disable-doc '
        --disable-decoder=libdav1d
        
    - name: Make
      shell: cmd
      run: cd FFmpeg && make

    - name: Make install
      shell: cmd
      run: cd FFmpeg && make install

    - name: List files
      shell: cmd
      run: echo "Listing files..." && ls ${{github.workspace}}/upload
    
    - name: List files again
      shell: cmd
      run: echo "List files again..." && ls ${{github.workspace}}/FFmpeg
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-artifact
        path: ${{github.workspace}}/upload
        if-no-files-found: ignore
        retention-days: 0
