name: Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install nasm
      
    - name: Build library
      run: |
        git clone https://github.com/FFmpeg/FFmpeg.git
        cd FFmpeg
        ./configure \
        --arch=x86_64 \
        --target-os=linux \
        --enable-gpl \
        --disable-static \
        --enable-shared \
        --disable-programs \
        --disable-doc \
        --disable-decoder=libdav1d
        
    - name: Make
      run: cd FFmpeg && make

    - name: Make install
      run: cd FFmpeg && sudo make install
