name: Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install nasm
      
    - name: Configure library
      run: |
        git clone https://github.com/FFmpeg/FFmpeg.git
        mkdir upload
        cd FFmpeg
        echo "Running git branch..."
        git branch
        echo "Running git checkout..."
        git checkout release/7.1
        echo "Running git status..."
        git status
        echo "Running configure..."
        ./configure \
        --arch=x86_64 \
        --target-os=linux \
        --prefix=${{github.workspace}}/upload \
        --enable-gpl \
        --disable-static \
        --enable-shared \
        --disable-programs \
        --disable-doc \
        --disable-decoder=libdav1d
        
    - name: Build library
      run: cd FFmpeg && make

    - name: Install library
      run: cd FFmpeg && sudo make install
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Linux-artifact
        path: ${{github.workspace}}/upload
        if-no-files-found: ignore
        retention-days: 0
