name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: msys2/setup-msys2@v2
      with:
        install: >-
          autoconf
          automake
          diffutils
          libtool
          make
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-tools
          nasm
          pkg-config
          yasm
        path-type: inherit
        update: true

    - name: Setup MSYS2
      shell: msys2 {0}
      run: mv /usr/bin/link.exe /usr/bin/link.exe.bak
        
    - name: Clone FDK-AAC
      shell: cmd
      run: |
        mkdir C:\fdk-aac
        git clone https://github.com/mstorsjo/fdk-aac.git
        cd fdk-aac
        git checkout 716f4394641d53f0d79c9ddac3fa93b03a49f278

    - name: Setup FDK-AAC
      working-directory: ${{github.workspace}}/fdk-aac
      shell: msys2 {0}
      run: |
        libtoolize
        aclocal
        autoconf
        automake --add-missing

    - name: Configure FDK-AAC
      working-directory: ${{github.workspace}}/fdk-aac
      shell: msys2 {0}
      run: ./configure --prefix=/c/fdk-aac

    - name: Build FDK-AAC
      working-directory: ${{github.workspace}}/fdk-aac
      shell: msys2 {0}
      run: make

    - name: Install FDK-AAC
      working-directory: ${{github.workspace}}/fdk-aac
      shell: msys2 {0}
      run: make install
        
    - name: Clone FFmpeg
      shell: cmd
      run: |
        mkdir c:\upload
        git clone https://github.com/faojdoai324234s/FFmpeg.git
        cd FFmpeg
        git checkout e038a48d08b9c3768168eec11a741d1ddc69ee8a

    - name: Run configure script
      shell: cmd
      run: |
        msys2 -c ./build_win.bat

    - name: Upload log
      uses: actions/upload-artifact@v4
      with:
        name: ffbuild-log
        path: ${{github.workspace}}/FFmpeg/ffbuild
        if-no-files-found: ignore
        include-hidden-files: true
        retention-days: 0

    - name: Build library
      working-directory: ${{github.workspace}}/FFmpeg
      shell: msys2 {0}
      run: make

    - name: Install library
      working-directory: ${{github.workspace}}/FFmpeg
      shell: msys2 {0}
      run: make install
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-artifact
        path: ${{github.workspace}}/upload
        if-no-files-found: ignore
        include-hidden-files: true
        retention-days: 0
