name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Build project
      shell: cmd
      run: |
        rename lib\*.a lib\*.lib
        cmake -B build -D CMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-artifact
        path: ${{github.workspace}}/build/Release/*.exeeeeee
        if-no-files-found: ignore
        include-hidden-files: true
        retention-days: 0
